# Generated by Django 5.0.2 on 2024-04-02 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('command', models.TextField()),
                ('estimated_time', models.DurationField()),
                ('slack_time', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('success', models.BooleanField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelTable(
            name='logrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ptpendpoint',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ptpprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sample',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tag',
            table=None,
        ),
    ]
