# Generated by Django 5.0.2 on 2024-04-03 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_scheduletask_completion_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptpendpoint',
            old_name='clock_diff_p99',
            new_name='clock_diff_p95',
        ),
    ]
