# Generated by Django 5.0.2 on 2024-03-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ptpendpoint_restart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptpprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='ptpprofile',
            name='is_corrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ptpprofile',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ptpprofile',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ptpprofile',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
