# Generated by Django 5.0.2 on 2024-04-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_clock_diff_p99_ptpendpoint_clock_diff_p95'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='clock_diff_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='path_delay_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='path_delay_p95',
            field=models.FloatField(null=True),
        ),
    ]
