# Generated by Django 5.0.2 on 2024-04-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ptpendpoint_clock_diff_p05_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletask',
            options={'ordering': ('id',)},
        ),
    ]
