# Generated by Django 5.0.2 on 2024-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ptpprofile_state_ptpprofile_is_corrupted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='value',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
