# Generated by Django 5.0.2 on 2024-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_scheduletask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpprofile',
            name='cluster_id',
            field=models.CharField(default='Raspberry-Pi 4', max_length=255),
            preserve_default=False,
        ),
    ]
