# Generated by Django 5.0.2 on 2024-03-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sample_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
