# Generated by Django 5.0.2 on 2024-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ptpprofile_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='path_delay_std',
            field=models.FloatField(null=True),
        ),
    ]
