# Generated by Django 5.0.2 on 2024-03-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_convergence_time_ptpendpoint_convergence_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='clock_step_magnitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='clock_step_timestamp',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
