# Generated by Django 5.0.2 on 2024-04-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_ptpendpoint_path_delay_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='cluster_id',
            field=models.CharField(default='rpi-4', max_length=255),
            preserve_default=False,
        ),
    ]
