# Generated by Django 5.0.2 on 2024-04-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ptpendpoint_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptpendpoint',
            name='cluster_id',
        ),
    ]
