# Generated by Django 5.0.2 on 2024-03-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ptpendpoint_clock_step_magnitude_and_more'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='logrecord',
        #     options={'ordering': ('id',)},
        # ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MASTER', 'Master'), ('PRIMARY_SLAVE', 'Primary Slave'), ('SECONDARY_SLAVE', 'Secondary Slave'), ('ORCHESTRATOR', 'Orchestrator')], default='UNKNOWN', max_length=32),
        ),
        migrations.AlterField(
            model_name='logrecord',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_diff_median',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_diff_p99',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_step_magnitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_step_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_max_offset',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='path_delay_median',
            field=models.FloatField(null=True),
        ),
        # migrations.AlterModelTable(
        #     name='logrecord',
        #     table='ptp_perf_logrecord',
        # ),
        # migrations.AlterModelTable(
        #     name='ptpendpoint',
        #     table='ptp_perf_ptpendpoint',
        # ),
        # migrations.AlterModelTable(
        #     name='ptpprofile',
        #     table='ptp_perf_ptpprofile',
        # ),
        # migrations.AlterModelTable(
        #     name='sample',
        #     table='ptp_perf_sample',
        # ),
        # migrations.AlterModelTable(
        #     name='tag',
        #     table='ptp_perf_tag',
        # ),
    ]
