# Generated by Django 5.0.2 on 2024-04-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_logrecord_options_ptpendpoint_endpoint_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logrecord',
            options={'ordering': ('id',)},
        ),
    ]
