# Generated by Django 5.0.2 on 2024-04-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_ptpendpoint_cluster_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
