# Generated by Django 5.0.2 on 2024-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_scheduletask_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSummary',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('benchmark_id', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=255)),
                ('cluster_id', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('clock_diff_median', models.FloatField(null=True)),
                ('clock_diff_p05', models.FloatField(null=True)),
                ('clock_diff_p95', models.FloatField(null=True)),
                ('path_delay_median', models.FloatField(null=True)),
                ('path_delay_p05', models.FloatField(null=True)),
                ('path_delay_p95', models.FloatField(null=True)),
                ('path_delay_std', models.FloatField(null=True)),
            ],
        ),
    ]
