# Generated by Django 5.0.2 on 2024-04-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_benchmarksummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptpendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MASTER', 'Master'), ('PRIMARY_SLAVE', 'Primary Slave'), ('SECONDARY_SLAVE', 'Secondary Slave'), ('ORCHESTRATOR', 'Orchestrator'), ('SWITCH', 'Switch')], default='UNKNOWN', max_length=32),
        ),
    ]
