# Generated by Django 5.0.2 on 2024-04-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_ptpendpoint_endpoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_actual_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_p95',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_p95',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_p95',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_p05',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_p95',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_ratio_clock_diff_median',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_ratio_clock_diff_p95',
            field=models.FloatField(null=True),
        ),
    ]
