# Generated by Django 5.0.2 on 2024-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_ptpendpoint_fault_actual_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='endpoint-fault',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.ptpendpoint',),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='fault_clock_diff_post_max_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='fault_clock_diff_post_max_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='fault_ratio_clock_diff_post_max_pre_median_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_ratio_clock_diff_post_max_pre_median',
            field=models.FloatField(null=True),
        ),
    ]
