# Generated by Django 5.0.2 on 2024-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_endpoint_fault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='secondary_fault_clock_diff_post_max_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='secondary_fault_clock_diff_post_max_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='secondary_fault_ratio_clock_diff_post_max_pre_median_mean',
            field=models.FloatField(null=True),
        ),
    ]
