# Generated by Django 5.0.2 on 2024-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_ptpendpoint_proc_cpu_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_cpu_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_cpu_percent_system',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_cpu_percent_user',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_ctx_switches_involuntary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_ctx_switches_voluntary',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_io_read_bytes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_io_read_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_io_write_bytes',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_io_write_count',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_mem_rss',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_mem_vms',
            field=models.FloatField(null=True),
        ),
    ]
