# Generated by Django 5.0.2 on 2024-04-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_benchmarksummary_proc_cpu_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='summary-resources-consumption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.benchmarksummary',),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_bytes_received',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_bytes_sent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_packets_received',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_packets_sent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_bytes_received',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_bytes_sent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_packets_received',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_packets_sent',
            field=models.FloatField(null=True),
        ),
    ]
