# Generated by Django 5.0.2 on 2024-04-30 17:13

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_summary_resources_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_cpu_percent',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_cpu_percent_system',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_cpu_percent_user',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_ctx_switches_involuntary',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_ctx_switches_voluntary',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_io_read_bytes',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_io_read_count',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_io_write_bytes',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_io_write_count',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_mem_rss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='proc_mem_vms',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_bytes_received',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_bytes_sent',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_packets_received',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_packets_sent',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
    ]
