# Generated by Django 5.0.2 on 2024-04-30 18:58

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_benchmarksummary_proc_cpu_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarksummary',
            name='clock_diff_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='clock_diff_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='clock_diff_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='fault_clock_diff_post_max_max',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='fault_clock_diff_post_max_min',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='path_delay_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='path_delay_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='path_delay_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='path_delay_std',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='secondary_fault_clock_diff_post_max_max',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='secondary_fault_clock_diff_post_max_min',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
    ]
