# Generated by Django 5.0.2 on 2024-04-30 23:09

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_benchmarksummary_clock_diff_median_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='summary-resources-consumption',
        ),
        migrations.CreateModel(
            name='endpoint-resource-consumption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.ptpendpoint',),
        ),
        migrations.CreateModel(
            name='summary-resource-consumption',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.benchmarksummary',),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_mem_pss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='proc_mem_uss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='proc_mem_pss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='proc_mem_uss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_diff_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_diff_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='clock_diff_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='path_delay_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='path_delay_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='path_delay_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='path_delay_std',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_cpu_percent',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_cpu_percent_system',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_cpu_percent_user',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_ctx_switches_involuntary',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_ctx_switches_voluntary',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_io_read_bytes',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_io_read_count',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_io_write_bytes',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_io_write_count',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_mem_rss',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='proc_mem_vms',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_bytes_received',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_bytes_sent',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_packets_received',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_packets_sent',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
    ]
