# Generated by Django 5.0.2 on 2024-04-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_ptpendpoint_sys_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_cpu_frequency',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_sensors_temperature_cpu',
            field=models.FloatField(null=True),
        ),
    ]
