# Generated by Django 5.0.2 on 2024-05-01 00:20

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_benchmarksummary_sys_cpu_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_bytes_total',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='sys_net_ptp_iface_packets_total',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_bytes_total',
            field=ptp_perf.utilities.django_utilities.DataFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='sys_net_ptp_iface_packets_total',
            field=ptp_perf.utilities.django_utilities.GenericEngineeringFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_cpu_frequency',
            field=ptp_perf.utilities.django_utilities.FrequencyFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='sys_sensors_temperature_cpu',
            field=ptp_perf.utilities.django_utilities.TemperatureFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_cpu_frequency',
            field=ptp_perf.utilities.django_utilities.FrequencyFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='sys_sensors_temperature_cpu',
            field=ptp_perf.utilities.django_utilities.TemperatureFormatFloatField(null=True),
        ),
    ]
