# Generated by Django 5.0.2 on 2024-05-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_benchmarksummary_sys_net_ptp_iface_bytes_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='resource_profile_length',
            field=models.DurationField(null=True),
        ),
    ]
