# Generated by Django 5.0.2 on 2024-05-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_ptpendpoint_resource_profile_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLogRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(10, 'Debug'), (20, 'Info'), (30, 'Warning'), (40, 'Error'), (50, 'Critical')], help_text='The level of importance of the message.')),
                ('timestamp', models.DateField()),
                ('message', models.TextField(null=True)),
                ('profile', models.ForeignKey(help_text='The profile being analyzed.', on_delete=django.db.models.deletion.CASCADE, to='app.ptpprofile')),
            ],
        ),
    ]
