# Generated by Django 5.0.2 on 2024-05-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_ptpendpoint_endpoint_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletask',
            options={'ordering': ('-priority', '-id')},
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
