# Generated by Django 5.0.2 on 2024-05-10 18:10

import ptp_perf.utilities.django_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_scheduletask_options_scheduletask_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletask',
            options={'ordering': ('-completion_time', '-priority', 'id')},
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='missing_samples_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='missing_samples_percent',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
