# Generated by Django 5.0.2 on 2024-05-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_scheduletask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptpprofile',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
