# Generated by Django 5.0.2 on 2024-05-10 18:41

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import Max


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PTPProfile = apps.get_model("app", "PTPProfile")
    LogRecord = apps.get_model("app", "LogRecord")
    for profile in PTPProfile.objects.all():
        previous_stop_time = profile.stop_time
        profile.stop_time = LogRecord.objects.filter(endpoint__profile__id__exact=profile.id).aggregate(
            Max('timestamp')
        )['timestamp__max']
        print(f'Updated profile {profile} stop time from {previous_stop_time} to {profile.stop_time} based off of log records.')
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_ptpprofile_stop_time'),
    ]

    operations = [
        RunPython(combine_names)
    ]
