# Generated by Django 5.0.2 on 2024-05-10 20:14

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20240510_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='clock_diff_max',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='path_delay_max',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
    ]
