# Generated by Django 5.0.2 on 2024-05-14 21:07

from django.db import migrations
from django.db.migrations import RunPython


def archive(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PTPProfile = apps.get_model("app", "PTPProfile")
    for profile in PTPProfile.objects.filter(vendor_id='sptp', cluster_id__in=['rpi-5', 'petalinux']):
        profile.vendor_id = 'sptp-soft-ts'
        print(f'Archived profile {profile}.')
        profile.save()

    BenchmarkSummary = apps.get_model("app", "BenchmarkSummary")
    for summary in BenchmarkSummary.objects.filter(vendor_id='sptp', cluster_id__in=['rpi-5', 'petalinux']):
        print(f'Deleting summary {summary}.')
        summary.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_benchmarksummary_clock_diff_max_and_more'),
    ]

    operations = [
        RunPython(archive)
    ]
