# Generated by Django 5.0.2 on 2024-05-15 19:37

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_archive_sptp_software_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='clock_diff_p99',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='path_delay_p99',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
    ]
