# Generated by Django 5.0.2 on 2024-05-15 20:53

import ptp_perf.utilities.django_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_benchmarksummary_clock_diff_p99_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='converged_percentage',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='converged_samples',
            field=models.IntegerField(null=True),
        ),
    ]
