# Generated by Django 5.0.2 on 2024-05-17 08:22

import ptp_perf.utilities.django_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_ptpendpoint_fault_clock_diff_return_to_normal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='converged_percentage',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='converged_samples',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='convergence_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='convergence_max_offset',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='convergence_rate',
            field=models.FloatField(null=True),
        ),
    ]
