# Generated by Django 5.0.2 on 2024-05-17 09:45

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_benchmarksummary_converged_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='missing_samples_percent',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='convergence_max_offset',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='benchmarksummary',
            name='convergence_rate',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_max_offset',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='convergence_rate',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
    ]
