# Generated by Django 5.0.2 on 2024-05-18 02:26

import ptp_perf.utilities.django_utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_benchmarksummary_missing_samples_percent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='benchmarksummary',
            old_name='missing_samples_percent',
            new_name='missing_samples_primary_percent',
        ),
        migrations.AddField(
            model_name='benchmarksummary',
            name='missing_samples_all_percent',
            field=ptp_perf.utilities.django_utilities.PercentageFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_post_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_clock_diff_pre_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_post_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_median',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_p05',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='fault_path_delay_pre_p95',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
    ]
