# Generated by Django 5.0.2 on 2024-05-20 07:26

import ptp_perf.utilities.django_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_sample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='fault_clock_diff_mid_max_max',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='fault_clock_diff_mid_max',
            field=models.FloatField(null=True),
        ),
    ]
