# Generated by Django 5.0.2 on 2024-05-24 11:43

import ptp_perf.utilities.django_utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_benchmarksummary_fault_clock_diff_mid_max_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksummary',
            name='clock_diff_mean',
            field=ptp_perf.utilities.django_utilities.TimeFormatFloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ptpendpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('MASTER', 'Master'), ('PRIMARY_SLAVE', 'Primary Slave'), ('SECONDARY_SLAVE', 'Secondary Slave'), ('TERTIARY_SLAVE', 'Tertiary Slave'), ('ORCHESTRATOR', 'Orchestrator'), ('SWITCH', 'Switch'), ('SLAVE_ANY', 'Special Slave Any')], default='UNKNOWN', max_length=32),
        ),
    ]
