# Generated by Django 5.0.2 on 2024-03-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PTPProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('benchmark', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('valid', 'Valid')], max_length=255)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('benchmark', 'Benchmark'), ('machine', 'Machine')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PTPEndpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=255)),
                ('clock_diff_median', models.FloatField(editable=False, null=True)),
                ('clock_diff_p99', models.FloatField(editable=False, null=True)),
                ('path_delay_median', models.FloatField(editable=False, null=True)),
                ('convergence_time', models.DateTimeField(editable=False, null=True)),
                ('convergence_max_offset', models.FloatField(editable=False, null=True)),
                ('convergence_rate', models.FloatField(editable=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptp_perf.ptpprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptp_perf.ptpprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sample_type', models.CharField(choices=[('CLOCK_DIFF', 'Clock Diff'), ('PATH_DELAY', 'Path Delay'), ('FAULT', 'Fault')], max_length=255)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptp_perf.ptpendpoint')),
            ],
        ),
    ]
