# Generated by Django 5.0.2 on 2024-03-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptp_perf', '0002_rename_benchmark_ptpprofile_benchmark_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrecord',
            name='profile',
        ),
        migrations.AddField(
            model_name='logrecord',
            name='endpoint',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ptp_perf.ptpendpoint'),
            preserve_default=False,
        ),
    ]
