# Generated by Django 5.0.2 on 2024-03-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptp_perf', '0003_remove_logrecord_profile_logrecord_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptpendpoint',
            name='restart_count',
            field=models.IntegerField(default=0),
        ),
    ]
