# Generated by Django 5.0.2 on 2024-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptp_perf', '0007_alter_sample_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptpendpoint',
            old_name='convergence_time',
            new_name='convergence_timestamp',
        ),
        migrations.AddField(
            model_name='ptpendpoint',
            name='convergence_duration',
            field=models.DurationField(editable=False, null=True),
        ),
    ]
